### ISSUE TITLE
FreeStyle SVG fills

### ISSUE THREAD

**Issue by anonimo82** [folkertdev/freestyle-svg-exporter#10]
Hello everyone. As requested, I'm posted a less-cluttered issue for this.
Basically, what I'd like to do is export fills correctly from FreeStyle SVG exporter.
I done a simple scene with Blender 2.49c and VRM (Vector Rendering Method), here it is:

https://drive.google.com/open?id=1r5LY-3KlHjQ42ZPsYt0SHTYRnWdTDF3A

Here is the VRM extension for Blender 2.4x: https://vrm.ao2.it/section/en/files/download.html

Note I guess you need the old Blender version to open the .blend

Edit: Check out the website for examples and more: https://vrm.ao2.it/

**Comment by folkertdev** [comment]
Yea this stuff is pretty old at this point, and it uses the actual mesh to generate the output (So I think this would fail on curves/nurbs/metaballs etc.). Anyway, it has nothing to do with freestyle at all. You could try to update the script for current blender versions and overlay the output.

**Comment by anonimo82** [comment]
I can't, I'm not a developer.
By the way, you're right: I just tried with a NURBS surface and it won't render.
But I guess you can mimic the algorithm for exporting fills.

**Comment by anonimo82** [comment]
Please, I would pay if you need

**Comment by anonimo82** [comment]
Nevermind, I found this: https://github.com/mrossini-ethz/vector-render
It does exactly what I need. Thanks anyhow.

**Comment by anonimo82** [comment]
FYI: Look here: https://drive.google.com/open?id=18n5e-yCuF_s-N7L4ByVaPgIK8p_VLyXr
