### ISSUE TITLE
Per face material fill

### ISSUE THREAD

**Issue by anonimo82** [folkertdev/freestyle-svg-exporter#11]
Hello everyone.
I'd like FreeStyle SVG exporter to correctly export fills as in this script: https://github.com/mrossini-ethz/vector-render

Basically, this script uses flat shading and has basic light support, but the most important thing is that this correctly export fils (per-face material, flat shading).
Here is a sample render: https://drive.google.com/open?id=18n5e-yCuF_s-N7L4ByVaPgIK8p_VLyXr

Please, make SVG Exporter look like this.

Thanks if you do.

**Comment by anonimo82** [comment]
May I have some feedback?

**Comment by xuv** [comment]
@anonimo82 Thx for the suggestion. Indeed, it's a nice proposition. Though I can't speak on the feasibility of it.

What I'm curious of is if you already a have a script that does it the way you want it, why would you want it to be added to this freestyle-svg-exporter? What is missing from that script that SVG exporter has?

Another thing to take into consideration is that everyone around this project is doing this on their free time. So if you don't have an immediate answer to your question, please be patient, or try to find someone you know who can help you with this.

**Comment by anonimo82** [comment]
Because FS renders whatever geometry, not only polygons, and because FS also renders animations.

**Comment by xuv** [comment]
@anonimo82 Thx for the information. I see that similar discussions have already happened in issues #8 & #10. I understand that you are actively looking for this feature. I'm not usre @folkertdev will have the time to do this. Best would be to find a developer interested in your project and that would help you "merge" these two pieces of code. Maybe @folkertdev can flag this issue with a "help-requested" label so that other devs know they can jump in.

**Comment by anonimo82** [comment]
Yes, I-d really like that. Please, mark this as help-requested.
I asked the author of Vector render, but he said algorithms are different.
I instead guess this can be done.

**Comment by anonimo82** [comment]
I found a workaround: when using planes each "face" has its own material, so coloring is done right.
Now, I'm pretty sure there's a way to split a mesh in individual face (one plane per face), but I don't know which is.
Sideways, can I still treat separate planes as a single mesh by grouping?

Thanks a lot to who'll help.

**Comment by anonimo82** [comment]
Dear, I got the problem.
It's just a z-sorting issue.

In fact, when a geometry is bigger, nearer meshes are drawn with the same material of the big one.
Try making a plane and scale it up, then put a cube in front of it (looking from camera) and assign different materials: the cube will render with the plane's material.

I'm attaching a test scene with renderings, both SVG and png.

I hope this will be sorted out.

Bue, Ivano.

[Blender.zip](https://github.com/folkertdev/freestyle-svg-exporter/files/2476261/Blender.zip)

**Comment by anonimo82** [comment]
Here another experiment: I tried to render 2 planes in 3 angles.
When put horizontally, both use the same material.
When put vertically, plane colors are uniform when normals face camera, with artifacts otherwise.

I hope this helps, I'm attaching .blend files with renders.
[planes.zip](https://github.com/folkertdev/freestyle-svg-exporter/files/2478830/planes.zip)

**Comment by anonimo82** [comment]
Dear, this time I got it for real.
It's a normal issue, geometry is rendered correctly only if mormals' orientarion angle is <90° than the camera direction.
I'm attaching an example.

If I'm right, all is needed is to flip normals before rendering.

Planes render correctly in any way, I guess because they have no volume.
Intetsecting geometry still causes artifacts.

Bye, Ivano.
[correct.zip](https://github.com/folkertdev/freestyle-svg-exporter/files/2480420/correct.zip)

**Comment by anonimo82** [comment]
SVG rendering works too oddly to find any issue without stepping the code while it runs.
Sometimes it works if I reverse normals, other times works if I split a mesh in planes, etc.

It's very buggy indeed.

**Comment by folkertdev** [comment]
In general, Freestyle is very sensitive to small changes in the geometry, this is not something I can easily fix in the addon. It looks like LNPR brings some improvements in this area.

**Comment by anonimo82** [comment]
Excuse me, what is NLPR?
