### ISSUE TITLE
File naming for a still or frame

### ISSUE THREAD

**Issue by xuv** [folkertdev/freestyle-svg-exporter#2]
I've noticed that when you render a single frame, it adds a number to the filename.
Although this might be interesting if you have an animation (of which you just want to render one frame), it's a bit "annoying" when just rendering a single illustration (not part of an animation).
Don't know if that can be an easy fix.

**Comment by folkertdev** [comment]
This was proposed by Campbell and seems to be in line with the saving of a still frame (a normal render). I may implement it as a setting though.

**Comment by xuv** [comment]
No worries. It's fine like that. It's my mistake actually. I thought that when we were rendering just one image [F12], it would automatically save it with the directory/name mentioned in the "output" panel mentioned in render properties. But actually, that's not true. One must click "save as" or [F3] and choose a name for the render file. Only when using "Render Animation" button that it renders automatically to that folder and then automatically happens  a frame number. So you addon behaves as expected. Don't bother adding an extra option. Thx.
