### ISSUE TITLE
How to set stroke colors?

### ISSUE THREAD

**Issue by StrandedAlien** [folkertdev/freestyle-svg-exporter#22]
Hello, Thanks for the wonderful plugin. It is just awesome and very useful for technical documentation. Would it be possible to add the possibility to let the strokes inherit the vertex color? Or set some color for part of the strokes. At the moment i can only change the color of all the strokes together. Meaning i have to retouch every graphic with Inkscape to get the desired result. According to the plugin menues it appears that this is already possible. What did i miss, or is it a bug?

EDIT: Nevermind, i found it. Plugins stroke color has to be set via
![image](https://user-images.githubusercontent.com/89656885/218287096-8a1bb069-fc07-46e3-b0a0-42688106b5c6.png)

Select object or part of object and assign the material like usual. Line color is in the material settings scroll down a bit.

Man, i am happy now. Missed that for years. Great, really great plugin. You are the man.
![image](https://user-images.githubusercontent.com/89656885/218287241-651e871f-4c5f-4ee6-9c0a-3936949f7a2a.png)

[4col_strokes.blend.zip](https://github.com/folkertdev/freestyle-svg-exporter/files/10715033/4col_strokes.blend.zip)

You may close the issue. Solved.

**Comment by folkertdev** [comment]
glad you like it!
