### ISSUE TITLE
Fill contours is generated for every lineset

### ISSUE THREAD

**Issue by xuv** [folkertdev/freestyle-svg-exporter#5]
Hello @folkertdev 

It seems that there is a fill generated for every Lineset defined in Freestyle. And I'm not really sure this is intended behavior.

In this particular case where I'm trying to have external contour lines that are different from the inside lines, if I have the "Fill Contours" option enabled, it renders fills for both lineset and so it "hides" the fill of one lineset hides the lines from the other lineset.

Here are is a practical example. 
![uhbench-debug-fillcontour](https://cloud.githubusercontent.com/assets/192539/7969969/bc838a78-0a08-11e5-9eb2-345e3f4e94f8.png)

(Sorry, Github does not want me to upload SVG. So this is SVG rendered in PNG from Inkscape ;) )
I can send you the SVG files if you want them.

As I see it, for each lineset, the exporter creates a  <g> incorporating a <g> for fills and a <g> for strokes.

Maybe, if that's possible, it would be nice to (de-)activate the fill contours per lineset. 
Or just generate it once in it's own <g> tag, that is always beneath all the other <g> strokes.

**Edit:** Maybe a "quick hack" would be to compute the fills only on the first lineset and ignore for the following ones.

What do you think?

**Comment by folkertdev** [comment]
hello @xuv 

the exporter is invoked by the parameter editor (which is really a large style module builder). This means that it indeed runs once per lineset. 

Another important detail is that the fills use a completely new render process, i.e. they don't use the existing strokes but render/calculate new ones (that aren't visible, obviously). 

Now, turning off the exporter on a per-lineset basis should be possible, but is a little involved. I'll have a look at it next week.  As a quick fix, for now, you could play with the ordering of line sets (this should change which layer is on top) and maybe delete an obstructing fill layer in inkscape.

**Comment by xuv** [comment]
Hello @folkertdev 

It's kind of great news to know that the fills use their own render process. 
Which means you can totally separate that from the number of linesets defined by the user and just calculate it once per render (and not per lineset).

It would have then it's own <g id="Contour_Fill"> at the beginning of the file. And then a series of <g id="strokes"> afterwards.

I'm also thinking that since it's independent from the linesets defined by the user, it would be great to just render the fills if this is requested. 

So for example, if I just want to render a fill with no lines, I would just deactivate all linesets and just render with the option "Contour Fills" activated. It sound as something I would use.

As for now, I found a "hack" to solve my problem. I run a program called "XMLStarlet" over the rendered SVG to delete the <g id="flills"> that I don't want to keep. :) 

Here's what the result looks like ;)
![uhbench](https://cloud.githubusercontent.com/assets/192539/8008278/1b0f05ec-0b6f-11e5-895f-33788b2c328a.gif)

**Comment by folkertdev** [comment]
Hello Julien, 

I'm very sorry this took so long, but I've finally fixed this issue. 

The inclusion of both strokes and fills can now be configured for every line style. (due to technical reasons this can't be done per-lineset, even though that would seem more logical. I think though that the distinction doesn't really matter here.)

BTW, that gif is totally awesome

**Comment by xuv** [comment]
Hey. 

Thx for the update. It's works beautifully.
Thanks for taking the time to add this feature.
